spring.data.mongodb.uri=mongodb+srv://imashifernando20019_db_user:Imashi12345@cluster0.wq80bip.mongodb.net/mycampusswap?retryWrites=true&w=majority
spring.data.mongodb.database=mycampusswap

# Server Port
server.port=${PORT:10000}