spring.data.mongodb.uri=${MONGODB_URI}

server.port=${PORT:10000}

SECRET_API_KEY=${SECRET_API_KEY}

spring.data.mongodb.database=mycampusswap  
spring.main.banner-mode=off                
spring.jpa.hibernate.ddl-auto=update